# CS 345 Exercise 03:  NumPy

Solve the following exercises and submit the notebook via Canvas.

Everything you need for solving these exercises is contained in the [introduction to NumPy](https://github.com/asabenhur/CS345/blob/master/fall23/notebooks/module00_03_numpy.ipynb) notebook from the course github repository.

In [2]:
import numpy as np

### NaN and infinity

NumPy (and other computer languages/libraries) have a special value called `NaN` ([Not a Number](https://en.wikipedia.org/wiki/NaN)).
NaN is the result of various arithmetic operations, e.g. 0/0, $-\infty + \infty$.

In NumPy, NaN is represented as `np.nan`.  NaN satisfies the following properties:

* Comparisons of NaN with a number x using one of the operators =, <, >, >=, and <= is always False.  Consequently, x != NaN is always True.

* Any arithmetic operation involving a NaN leads to a NaN 

Infinity is represented using `np.inf`, and negative infinity is `-np.inf`.

* Experiment with NaN and infinity and convince yourself that the results of the following operations make sense to you:

```Pytnon
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - 1
```

In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - 1)

nan
False
False
nan


### Creating arrays

* Create a 3x3 matrix with the integer values from 0 to 8.  Do this by creating a one dimensional array and converting it to a two dimensional array using the [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function.

In [18]:
array = np.array([i for i in range(9)])
print(array)

array = array.reshape(3,3)
print(array)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


* Create the same 3x3 matrix and have the end result be a floating point array with a dtype `float64`.

In [23]:
array = np.array([i for i in range(9)])
array = array.reshape(3,3)

array = array.astype('float64')

print(array)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


* Create a vector (i.e. one dimensional array) of length 10 with random values between 0 and 1.

In [28]:

import random
vector = np.random.rand(10)
print(vector)

[0.35817984 0.43549912 0.45504394 0.39807191 0.04684189 0.58555311
 0.54136684 0.05616454 0.04618604 0.28019753]


* Create a 10x10 array with 1 on the border and 0 inside.

In [ ]:
array = np.

* For an integer $n$, create an array of length $3n$ filled with the cyclic pattern 1, 2, 3.  For example, for $n=2$, the resulting array should be ```[1,2,3,1,2,3]```.

### Slices

Describe the effect of each of the following slices of the following two-dimensional array, i.e. matrix:

```Python
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Describe it in terms of rows and columns of the matrix.  As an example consider the following slice:

Slice 1:
```Python
a2d[0]
```

*answer:  the first row of the matrix*  

This is an example to illustrate what we are looking for.

Slice 2:
```Python
a2d[1, :2]
```

*your answer here*

Slice 3:
```Python
a2d[:, -1]
```

*your answer here*

Slice 4:
```Python
a2d[:, 1:]
```

*your answer here*

Slice 5:
```Python
a2d[:,:]
```

*your answer here*

### Using NumPy Boolean arrays

* Replace all negative elements of the following array with the value 0.  This can be done with a single command! (Hint:  Boolean indexing).

In [ ]:
a = np.array([-1, 3, -2, -3, 5, 6, -2])
# your code here

* Write a command that replaces all NaN values with 0 in the following array.  Use [np.isnan](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html) with Boolean indexing.

In [ ]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
# your code here

### Computing data statistics

* Given the two dimensional array bellow, write code to compute the mean value of each column and display the result.  *Do not use for loops!*  Instead, use the `axis` keyword of `np.mean`.

In [ ]:
# computing column means of a 2d array.  You can use the following
# array as input.  Keep in mind that the result needs to be an array
# with 5 elements (same as the number of columns of the array)

a = np.array([[17.53, 18.55, 18.18, 10.8 , 10.08],
       [ 6.64, 15.78, 14.51, 12.4 , 14.6 ],
       [14.67,  2.02, 10.34,  3.79,  6.73],
       [12.61,  5.4 , 19.07, 13.76, 15.39],
       [ 1.82,  7.79,  5.41, 20.  , 18.17],
       [10.01,  8.88, 17.27,  1.73, 13.64]])

# your code below


### A slicing challenge

Here's a more challenging exercise that you can solve using slices:

* Create a 8x8 matrix that looks like this:

```Python
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]
```

Hint:  even and odd numbered rows each are filled with the same pattern.
